apiVersion: v1
kind: Service
metadata:
  labels: 
    app: frontend
  name: frontend
spec:
  type: NodePort
  ports:
  - name: "frontend-service"
    port: 80
    targetPort: 3000
    nodePort: 31001
  selector:
    app: frontend

    
