apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: frontend
  template:
    metadata:
      labels: 
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jdmghk/frontend
        ports:
        - containerPort: 80
          name: frontend

