apiVersion: v1
kind: Service
metadata:
  labels: 
    app: frontend
  name: frontend
spec:
  type: NodePort
  ports:
  - name: "frontend-service"
    port: 5001
    targetPort: 80
    NodePort: 31001
  selector:
    app: frontend

    
